### ISSUE TITLE
`enum` is reserved in Scala 3

### ISSUE THREAD

**Issue by armanbilge** [gemini-hlsw/lucuma-core#483]
Which puts the `enum` package in some trouble 😆 

Easiest is maybe to rename `enum` -> `enums`, I suppose also `adt` could be appropriate.

**Comment by tpolecat** [comment]
It's likely that most of these will go away, at least in this form, because their elements need to be fetched from the database at runtime. Rename makes sense. We could provide a deprecated `enum` object for Scala-2 that re-exports everything.

**Comment by cquiroz** [comment]
We may want to do this relatively soon and it should be easy to port all the dependencies if e.g. we rename to `enums`

**Comment by armanbilge** [comment]
Done in https://github.com/gemini-hlsw/lucuma-core/pull/542.
